### ISSUE TITLE
Failing to build .. :(

### ISSUE THREAD

**Issue by ptr1337** [JonasToth/llvm-bolt-builds#1]
Hey @JonasToth 

First thanks for those great scripts. 
I tried to build it, with some modifications since bolt it self changed some things and also tried to build the llvm 13 toolchain. 

BOLT itself it building fine with their new changes. But trying your latest bootstrapping script for full llvm did failed for me .
Also at your README.md is the git clone link not working, probally their is the issue? 

All in all, i got the toolchain built until one point when the toolchained clang-13 profiled itself. (after long time of building with a 5900x)

regards.

**Comment by JonasToth** [comment]
Hey @ptr1337 

to be honest, I just dumped the scripts here for my own reference. This was a work project and I did not retry it afterwards (my CPU doesn't have/had LBR, so bolt is not optimal). The read-me url is a reference to and internal company network.

It seems that the new mono-repo is already used, but the patching steps for BOLT are most likely incorrect.

Did you try a "LTO+PGO"-build only by outcommenting everything related to BOLT? I think this is the first thing that should work.
BOLT is then just another pass of gathering execution data and recompiling.
When I have time on the weekend or so I will try the stuff again. Until then I can probably just guess around. :/

How did clang-13 profile? Is it the normal PGO or did you use `perf`? Maybe something changed where to put the profile data or so?

Edit:
https://www.llvm.org/docs/AdvancedBuilds.html
This is the guide that contains "Bootstrap Builds - Multistage PGO". It should be approximately like it says. But I remember that I had to dig through the CMake a bit, but I don't recall exactly what the issues were.

**Comment by ptr1337** [comment]
Hey! 

Thanks for your Answer. 

I did run the FULL Boosttrap Profile first.... 

Now i fixed so far everything in your script. Maybe going to extend it more and more. 

Sadly i cant run the perf command on a amd cpu.

so i need to ask someone or just wait for bolts solution.

**Comment by JonasToth** [comment]
The `perf` command is dependent on the CPU counters (last-branch-record) that are not present on AMD (AFAIK).

Theoretically, you should be able to run this on an Intel-CPU and transfer the final binaries onto your AMD machine. It should still be faster!

Maybe [AutoFDO](https://gcc.gnu.org/wiki/AutoFDO) is something for you. I never did it on my own, but its a competing effort to Bolt. I think, they do not use the LBR, but I am not sure.

What parts did you need to fix? Could you maybe create a PR?

**Comment by ptr1337** [comment]
@JonasToth 

Yeah, ill overwork some stuff and then i will do a PR. 

Yeah, im searching right now a mate who will perf it for me.

**Comment by ptr1337** [comment]
#2
