### ISSUE TITLE
[Request] PKGBUILD for Arch Linux

### ISSUE THREAD

**Issue by ms178** [JonasToth/llvm-bolt-builds#3]
Hey Jonas,

I came across a fork of your repo with your scripts and tried it out myself today. This one is actually a request, I would like to ask you if it would be possible for you to build a PKGBUILD for Arch Linux users?! That way it would be easier to integrate such an optimized toolchain into the system as standard compiler.

**Comment by JonasToth** [comment]
@ptr1337 uses it for its own arch-based distribution.

Maybe that already exists? :)

**Comment by ptr1337** [comment]
Acutally there is no toolchain already implemented which is bolted. I compile weekly a llvm toolchain, which can be downloaded, but for now bolt is way to unstable when it optimizes something and has to play together with other system libaries. 

As I said, I can create a PKGBUILD, which can be bolted after the compilation of the PKGBUILD.

**Comment by ptr1337** [comment]
@ms178 

Check that PKGBUILD:
https://github.com/CachyOS/CachyOS-PKGBUILDS/blob/master/llvm/PKGBUILD

This will actually build a bootstrapped toolchain. You will be asked if you want to enable LTO. 
For a better understanding check this page:
https://llvm.org/docs/AdvancedBuilds.html

After you did built the PKGBUILD, you need to built the binary.

Check these two scripts if you have a cpu which does not support branch sampling and change the PATH's to the correct binary and you llvm-bolt stage 1 build.

https://github.com/ptr1337/llvm-bolt-scripts/blob/master/bolt-gcc-stage1.bash
https://github.com/ptr1337/llvm-bolt-scripts/blob/master/bolt-gcc-stage2.bash

Im not sure if the PKGBUILD is completly correct right now but feel free to PR.

**Comment by ms178** [comment]
@ptr1337 Thank you very much, it seems I was a few seconds too late. I've tried the llvm-bolt-scripts already, they do produce a working binary on my 18-Core Haswell-EP, but I had trouble compiling Mesa with it (see my other issue in this bug tracker here). I guess there is either some configuration option missing or was there a technical limitation to leave the dynamic llvm libs out?

**Comment by ptr1337** [comment]
@ms178 
Actually im not into mesa much. It could have something to do with the dynamic configuration, so there is definitely a option to disable this behavior, but I dont know how much this would affect the function of mesa.

Feel free to join the discord of cachyos or write me in discord to maybe get this fixed. Actually my goal is also the provide a complete llvm toolchain which is bolted and directly provided in the repo since we optimize already all arch packages with x86-64-v3 and also other optimizations.

With a intel cpu you can edit simply these path's and then bolt the binaries:
https://github.com/ptr1337/llvm-bolt-scripts/blob/master/build_stage3-bolt.bash

Here the discord:
https://discord.gg/qJqj94uFwE

**Comment by ms178** [comment]
@ptr1337 Thanks for the hints and for your work! I am a not a programmer, but over the last year tried experimentally to learn how to build an optimized toolchain to maximize the performance of my system (and Arch's default toolchain was in a dire state and still is). The fruits of that work are PKGBUILDs in my own repo, but as for advanced optimization techniques, I got only a LTO+PGOed GCC toolchain to work so far. My LLVM (+Polly) build is rather basic still. As you see in my PKGBUILDS, I aim for a minimal build (X86 with only C/C++ as supported language) to minimize the compilation times as it still takes a lot of time on that Haswell-EP system (at the cost of compatibility - this is only a basic toolchain for home users that want to tweak some C/C++ packages). I still need to dig deeper into your PKGBUILD, but as a frequent Polly user I'd like to suggest to add `-D LLVM_POLLY_LINK_INTO_TOOLS=ON \` as otherwise I faced a lot of trouble to use it with some build systems (e.g. Meson).

**Comment by JonasToth** [comment]
@ms178 bolt is not necessarily meant for dynamic libraries. what it does, is reorder the binary code such, that often executed segments are close to each other.
that might be different when mesa uses LLVM compared to when clang uses LLVM.

you can still try and you might get something out, but its not necessarily the design goal of bolt (and so not so well tested and the engineers have different priorities).

bolt is made for facebook (google has its own version called autoFDO) to optimize their _one_ binary that runs on thousand of servers and eats their money through electricity usage.
facebook is known to save millions in electricity costs alone, for every single percent their webapp gets faster.

another use case: you CI compiler for the project your working on. you can custom tailor the binary to that job and get something out of it.

so i think you might get a better experience with a working, normal toolchain and a fast statically linked `clang` binary.

**Comment by ptr1337** [comment]
Actually is seems not really useful to have a customized toolchain which is bolted with archlinux as system compiler. 
Actually through it depends to mesa, it will just create more and more issues.

**Comment by ms178** [comment]
As I understood it they optimize the layout for better data locality with their method. I've used Polly before for the same goal. However, it seems that there is a technical limitation with shared and dynamic libraries. I've burned through a lot of power through my CPU today (which showed signs of instability actually) but haven't gotten anywhere with my experiments. As I compile Mesa quite frequently, a compiler that can do this quickly is a priority for me. It seems I have to settle for LTO+PGO for now then. Thank you both regardless for your helpful comments.

**Comment by ptr1337** [comment]
Here you can find a bolted gcc-12. 
https://cloud.ptr1337.dev/s/koNjCxeg6eCKYeK

There binarys are in the .tar.gz which you have to move after the installation with pacman, if you want to bolt it yourself, the profile for optimatzion is also in :)

**Comment by ms178** [comment]
@ptr1337 If you are interested, here are my binaries (LTO+PGO + Clear Linux + Mailing List patches) for a shootout which is faster... https://drive.google.com/drive/folders/1-Fl8tkAtFbL4uXQP8x77SEivdBXsePzf?usp=sharing

Only C/C++ support though... see the PKGBUILDs in my Github repo if you want to see the details.

**Comment by ms178** [comment]
@ptr1337 The numbers from a small comparison with Mesa-git might be of interest.

GCC-ms178

real    2m11,414s
user    45m14,040s
sys     1m44,859s

GCC-ptr1337

real    1m51,086s
user    41m13,427s
sys     1m35,968s

That's a nice compile time improvement over my LTO+PGO build! The binary produced by your compiler is also around 3 MB smaller (likely due to the Clear Linux patches for my GCC that vectorize more).

The flags used were:

CFLAGS="-O3 -march=native -fno-semantic-interposition -falign-functions=32 -fipa-pta -flive-range-shrinkage -fno-math-errno -fno-trapping-math -mtls-dialect=gnu2 -feliminate-unused-debug-types -floop-nest-optimize -fgraphite-identity -fcf-protection=none -pipe -flto=auto -floop-parallelize-all -ftree-parallelize-loops=18 -fdevirtualize-at-ltrans -mharden-sls=none -fomit-frame-pointer"
CXXFLAGS="$CFLAGS"
LDFLAGS="$CFLAGS -Wl,-O3,--as-needed,-Bsymbolic-functions,-flto=auto -fopenmp"
ASFLAGS="-D__AVX__=1 -D__AVX2__=1 -D__FMA__=1"

**Comment by ms178** [comment]
I am closing this, as BOLT for LLVM/Clang seems to be not usable as system compiler due to technical limitations currently.
